{
 "title": "Produced and consumed",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Message queue size",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 0 },
   "targets": [
    { "expr": "message_queue_size", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Produced - Consumed",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 7 },
   "targets": [
    {
     "expr": "rate(messages_produced_total[$__rate_interval])\n-\nrate(messages_consumed_total[$__rate_interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Consumed per minute",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 15 },
   "targets": [
    {
     "expr": "rate(messages_consumed_total[$__rate_interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Produced per minute",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 23 },
   "targets": [
    {
     "expr": "rate(messages_produced_total[1m])",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}