name: Renovate
on:
  schedule:
    - cron: '30 17 * * *'
  workflow_dispatch:
    inputs:
      name:
        description: Test
jobs:
  renovate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.3.0
      - uses: renovatebot/github-action@v34.153.1
        with:
          token: ${{ secrets.RENOVATE_TOKEN }}
        env:
          LOG_LEVEL: debug
          RENOVATE_PLATFORM: github
          RENOVATE_ONBOARDING: 'false'
          RENOVATE_REQUIRE_CONFIG: 'false'
          RENOVATE_PRUNE_STALE_BRANCHES: 'false'
          RENOVATE_ENABLED_MANAGERS: 'gradle, docker-compose, dockerfile'
          RENOVATE_BRANCH_PREFIX: 'renovate/'
          RENOVATE_BRANCH_CONCURRENT_LIMIT: 15
          RENOVATE_PR_HOURLY_LIMIT: 15
          RENOVATE_REPOSITORIES: 'Czeffik/queues-performance'
          RENOVATE_BINARY_SOURCE: install
          RENOVATE_NPMRC_MERGE: 'true'
          RENOVATE_REBASE_WHEN: 'auto'
          RENOVATE_PLATFORM_AUTOMERGE: 'true'
          RENOVATE_ASSIGN_AUTOMERGE: 'true'
          RENOVATE_COMMIT_MESSAGE_PREFIX: 'RENOVATE '
          RENOVATE_CONFIG: >
            {
              "packageRules": [
                {
                  "matchUpdateTypes": ["minor", "patch", "pin", "digest"],
                  "automerge": true,
                  "automergeStrategy": "fast-forward"
                }
              ]
            }
